✨support file upload decorator
epiphone/routing-controllers-openapi pull request #76
Opened 2021-05-05 12:53 UTC by pondpiu

Support for @UploadedFile('fileName') and @UploadedFile('fileName') decorator

ref: #19

2021-07-10 02:07 UTC, epiphone requested changes
Thanks! Please add tests :)

2021-08-22 11:09 UTC, pondpiu commented
I've added some tests.

2021-09-07 13:43 UTC, donnyroufs commented
Any progress on this?

2021-11-18 13:29 UTC, cojack commented
@epiphone can you merge it?

2021-11-18 14:30 UTC, cojack approved these changes

2022-04-27 18:19 UTC, fhasni commented
This PR is not merged yet, Is there any additional work to be done on this?

2023-05-28 00:26 UTC, eum602 commented
Seems it is ready to be added to master. Is anything more needed to get it merged?.

2024-09-19 14:07 UTC, Fortur commented
Hello, @epiphone 
Can you merge this PR?

2025-02-09 03:23 UTC, epiphone approved these changes

2025-02-09 03:23 UTC, merged

2025-02-09 03:35 UTC, epiphone commented
Released in https://github.com/epiphone/routing-controllers-openapi/releases/tag/v4.1.0.